/**
 * Groups in Supabase.
 *
 * Table: `group_members`  — id, group_name, member (email), status ('invited'|'member'|'admin')
 *
 * Admins are rows in group_members where status = 'admin'.
 *
 * SQL (run in Supabase if missing):
 *
 *   create table if not exists public.group_members (
 *     id bigint generated by default as identity primary key,
 *     group_name text not null,
 *     member text not null,
 *     status text not null default 'invited'
 *   );
 */

let client = null;

function isConfigured() {
  return !!(process.env.SUPABASE_URL && process.env.SUPABASE_SERVICE_ROLE_KEY);
}

function getClient() {
  if (client) return client;
  if (!isConfigured()) return null;
  const { createClient } = require('@supabase/supabase-js');
  client = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
  return client;
}

function normalizeEmail(s) {
  return s != null ? String(s).trim().toLowerCase() : '';
}

/** Member statuses that give a user active membership in a group. */
const MEMBER_STATUSES = ['member', 'blind member', 'admin'];

/**
 * Returns group_member rows where member = userId AND status IN MEMBER_STATUSES,
 * plus admin_list (all members with status='admin' for that group) and is_admin flag.
 * Members are looked up case-insensitively.
 */
async function listGroupsForUser(userId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeEmail(userId);
  if (!uid) return [];

  // Fetch groups the user belongs to (member, blind member, or admin)
  const { data: memberRows, error: e1 } = await supabase
    .from('group_members')
    .select('*')
    .ilike('member', uid)
    .in('status', MEMBER_STATUSES)
    .order('group_name', { ascending: true });
  if (e1) throw e1;

  const groupNames = [...new Set((memberRows || []).map(r => r.group_name))];

  // For each group, fetch all rows where status = 'admin' to build the admin list
  const adminMap = {};
  // Fetch visibility from the groups table
  const visibilityMap = {};
  if (groupNames.length) {
    const [adminResult, groupsResult] = await Promise.all([
      supabase
        .from('group_members')
        .select('group_name, member')
        .in('group_name', groupNames)
        .eq('status', 'admin'),
      supabase
        .from('groups')
        .select('group_name, visibility')
        .in('group_name', groupNames)
    ]);
    if (adminResult.error) throw adminResult.error;
    if (groupsResult.error) throw groupsResult.error;

    for (const a of (adminResult.data || [])) {
      if (!adminMap[a.group_name]) adminMap[a.group_name] = [];
      adminMap[a.group_name].push(a.member);
    }
    for (const g of (groupsResult.data || [])) {
      visibilityMap[g.group_name] = g.visibility || null;
    }
  }

  // Deduplicate by group_name — a user may have both a 'member'/'blind member' and 'admin' row.
  // Keep one row per group, preferring the 'admin' row.
  const seen = {};
  for (const row of (memberRows || [])) {
    const existing = seen[row.group_name];
    if (!existing || row.status === 'admin') {
      seen[row.group_name] = row;
    }
  }

  return Object.values(seen).map(row => {
    const adminList = adminMap[row.group_name] || [];
    return {
      ...row,
      is_admin: adminList.map(a => normalizeEmail(a)).includes(uid),
      admin_list: adminList,
      visibility: visibilityMap[row.group_name] || null
    };
  });
}

/**
 * Returns group_member rows where member = userId AND status = 'invited'.
 */
async function listInvitesForUser(userId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeEmail(userId);
  if (!uid) return [];

  const { data, error } = await supabase
    .from('group_members')
    .select('*')
    .eq('member', uid)
    .eq('status', 'invited')
    .order('group_name', { ascending: true });
  if (error) throw error;
  return data || [];
}

/**
 * Accept a group invite:  set status = 'member' where id matches and member = invitee.
 * Reject a group invite:  delete the row where group_name + member match the invitee.
 * Only the invitee (member) may respond.
 */
async function respondToGroupInvite(id, userId, action) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeEmail(userId);
  if (action !== 'accept' && action !== 'reject') throw new Error('action must be accept or reject');

  const { data: row, error: selErr } = await supabase
    .from('group_members')
    .select('id, group_name, member, status')
    .eq('id', id)
    .maybeSingle();
  if (selErr) throw selErr;
  if (!row) return false;
  if (normalizeEmail(row.member) !== uid) return false;
  if (row.status !== 'invited') return false;

  if (action === 'accept') {
    const { error } = await supabase
      .from('group_members')
      .update({ status: 'member' })
      .eq('group_name', row.group_name)
      .eq('member', uid);
    if (error) throw error;
  } else {
    const { error } = await supabase
      .from('group_members')
      .delete()
      .eq('group_name', row.group_name)
      .eq('member', uid);
    if (error) throw error;
  }
  return true;
}

/**
 * Creates a new group and its initial members.
 *
 * @param {object} opts
 * @param {string}   opts.group_name
 * @param {string}   opts.visibility       e.g. 'Only me' | 'Members only' | 'Public'
 * @param {string}   opts.owner            email of the creating user (auto-added as 'member')
 * @param {string[]} opts.admins           emails assigned status 'admin'
 * @param {string[]} opts.invited_members  emails assigned status 'invited'
 */
async function createGroup({ group_name, visibility, owner, admins, invited_members }) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');

  const name = (group_name || '').trim();
  if (!name) throw new Error('group_name is required');
  const ownerEmail = normalizeEmail(owner);
  if (!ownerEmail) throw new Error('owner is required');

  // Insert the group row
  const { error: groupErr } = await supabase
    .from('groups')
    .insert({ group_name: name, visibility: visibility || null, owner: ownerEmail });
  if (groupErr) throw groupErr;

  // Build member rows — deduplicate by normalised email
  const memberRowMap = {};

  // Admins (always 'admin' regardless of visibility)
  for (const email of (admins || [])) {
    const e = normalizeEmail(email);
    if (e) memberRowMap[e] = { group_name: name, member: e, status: 'admin' };
  }

  // 'Only me' groups add people directly as members (no invite step).
  // All other visibility types send an invitation first.
  const newMemberStatus = visibility === 'Only me' ? 'member' : 'invited';

  for (const email of (invited_members || [])) {
    const e = normalizeEmail(email);
    if (e && !memberRowMap[e]) {
      memberRowMap[e] = { group_name: name, member: e, status: newMemberStatus };
    }
  }

  // Owner is a full member immediately (they created the group)
  if (!memberRowMap[ownerEmail]) {
    memberRowMap[ownerEmail] = { group_name: name, member: ownerEmail, status: 'member' };
  }

  const memberRows = Object.values(memberRowMap);
  if (memberRows.length) {
    const { error: membersErr } = await supabase.from('group_members').insert(memberRows);
    if (membersErr) throw membersErr;
  }

  return { group_name: name };
}

/**
 * Returns full details for a single group: group row + admins + members + invited_members.
 */
async function getGroupDetails(groupName) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');

  const ALL_STATUSES = [...MEMBER_STATUSES, 'invited'];

  const [groupResult, membersResult] = await Promise.all([
    supabase.from('groups').select('group_name, visibility, owner').eq('group_name', groupName).maybeSingle(),
    supabase.from('group_members').select('member, status').eq('group_name', groupName).in('status', ALL_STATUSES)
  ]);
  if (groupResult.error) throw groupResult.error;
  if (membersResult.error) throw membersResult.error;
  if (!groupResult.data) return null;

  const rows = membersResult.data || [];
  const admins = rows.filter(r => r.status === 'admin').map(r => r.member);
  const members = rows.filter(r => r.status === 'member' || r.status === 'blind member').map(r => r.member);
  const invited_members = rows.filter(r => r.status === 'invited').map(r => r.member);

  return { ...groupResult.data, admins, members, invited_members };
}

/**
 * Updates an existing group's visibility, admins, members, and invited_members.
 * Replaces all admin / member / blind member / invited rows entirely.
 */
async function updateGroup({ group_name, visibility, admins, members, invited_members, owner }) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');

  const name = (group_name || '').trim();
  if (!name) throw new Error('group_name is required');

  // Update the groups table row
  const update = {};
  if (visibility !== undefined) update.visibility = visibility;
  if (Object.keys(update).length) {
    const { error: upErr } = await supabase.from('groups').update(update).eq('group_name', name);
    if (upErr) throw upErr;
  }

  // 'Only me' groups use 'blind member' status for confirmed members
  const memberStatus = visibility === 'Only me' ? 'blind member' : 'member';

  // Replace all non-invited and invited rows
  const { error: delErr } = await supabase
    .from('group_members')
    .delete()
    .eq('group_name', name)
    .in('status', ['admin', 'member', 'blind member', 'invited']);
  if (delErr) throw delErr;

  const memberRowMap = {};

  // Admins
  for (const email of (admins || [])) {
    const e = normalizeEmail(email);
    if (e) memberRowMap[e] = { group_name: name, member: e, status: 'admin' };
  }

  // Confirmed members (don't downgrade an admin)
  for (const email of (members || [])) {
    const e = normalizeEmail(email);
    if (e && !memberRowMap[e]) memberRowMap[e] = { group_name: name, member: e, status: memberStatus };
  }

  // Invited members (don't downgrade an admin or confirmed member)
  for (const email of (invited_members || [])) {
    const e = normalizeEmail(email);
    if (e && !memberRowMap[e]) memberRowMap[e] = { group_name: name, member: e, status: 'invited' };
  }

  // Ensure owner always stays as a confirmed member
  const ownerEmail = normalizeEmail(owner);
  if (ownerEmail && !memberRowMap[ownerEmail]) {
    memberRowMap[ownerEmail] = { group_name: name, member: ownerEmail, status: memberStatus };
  }

  const rows = Object.values(memberRowMap);
  if (rows.length) {
    const { error: insErr } = await supabase.from('group_members').insert(rows);
    if (insErr) throw insErr;
  }
  return { group_name: name };
}

/**
 * Deletes a group and all its group_members rows.
 * Only the group owner or an admin may delete.
 * Returns { ok: true } or throws an error with a user-facing message.
 */
async function deleteGroup(groupName, userId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeEmail(userId);

  // Check ownership
  const { data: groupRow, error: gErr } = await supabase
    .from('groups').select('owner').eq('group_name', groupName).maybeSingle();
  if (gErr) throw gErr;
  if (!groupRow) throw Object.assign(new Error('Group not found'), { status: 404 });

  const isOwner = normalizeEmail(groupRow.owner) === uid;

  // Check admin status
  const { data: adminRow, error: aErr } = await supabase
    .from('group_members')
    .select('id')
    .eq('group_name', groupName)
    .ilike('member', uid)
    .eq('status', 'admin')
    .maybeSingle();
  if (aErr) throw aErr;

  if (!isOwner && !adminRow) {
    throw Object.assign(new Error('Only group admins can delete group'), { status: 403 });
  }

  // Delete all group_members first, then the group row
  const { error: delMembersErr } = await supabase.from('group_members').delete().eq('group_name', groupName);
  if (delMembersErr) throw delMembersErr;
  const { error: delGroupErr } = await supabase.from('groups').delete().eq('group_name', groupName);
  if (delGroupErr) throw delGroupErr;

  return { ok: true };
}

/**
 * Removes the user from a group's group_members rows (any status).
 */
async function leaveGroup(groupName, userId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeEmail(userId);

  const { error } = await supabase
    .from('group_members')
    .delete()
    .eq('group_name', groupName)
    .ilike('member', uid);
  if (error) throw error;
  return { ok: true };
}

/**
 * Returns the email addresses of all 'member' and 'blind member' rows for a group.
 */
async function getGroupMembers(groupName) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const { data, error } = await supabase
    .from('group_members')
    .select('member')
    .eq('group_name', groupName)
    .in('status', ['member', 'blind member']);
  if (error) throw error;
  return (data || []).map(r => r.member);
}

module.exports = {
  isConfigured,
  listGroupsForUser,
  listInvitesForUser,
  respondToGroupInvite,
  createGroup,
  getGroupDetails,
  updateGroup,
  deleteGroup,
  leaveGroup,
  getGroupMembers
};
