/**
 * Groups in Supabase.
 *
 * Table: `groups` — group_name, owner, visibility, handle (optional)
 * Table: `group_details` — display metadata for group pages: `group_name`, `handle` (matches URL segment after `/events/group/`; DB value is usually without `@`, e.g. `collegefriends_johnpicasso` for `@collegefriends_johnpicasso`)
 * Table: `group_members`  — group_name, group_handle (optional), member (email), status, person_handle (optional)
 *
 * Admins are rows in group_members where status = 'admin'.
 *
 * SQL (run in Supabase if missing):
 *
 *   create table if not exists public.group_members (
 *     id bigint generated by default as identity primary key,
 *     group_name text not null,
 *     member text not null,
 *     status text not null default 'invited'
 *   );
 *   alter table public.group_members add column if not exists person_handle text;
 *   alter table public.groups add column if not exists handle text;
 *   alter table public.group_members add column if not exists group_handle text;
 *
 *   create table if not exists public.group_details (
 *     handle text primary key,
 *     group_name text not null
 *   );
 */

let client = null;

function isConfigured() {
  return !!(process.env.SUPABASE_URL && process.env.SUPABASE_SERVICE_ROLE_KEY);
}

function getClient() {
  if (client) return client;
  if (!isConfigured()) return null;
  const { createClient } = require('@supabase/supabase-js');
  client = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
  return client;
}

const supabaseProfiles = require('./supabase-profiles');

function normalizeEmail(s) {
  return s != null ? String(s).trim().toLowerCase() : '';
}

/** Normalized public handle (no @), lowercased — matches `contact_details.contact_handle` / `group_members.person_handle`. */
function normalizePersonHandle(s) {
  return s != null ? String(s).trim().replace(/^@+/, '').toLowerCase() : '';
}

/** Lowercase [a-z0-9] only — used when auto-generating `groups.handle`. */
function alphanumericHandleSegment(s) {
  return String(s || '')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '');
}

/**
 * `groupName` + owner public handle (or email local-part), lowercased, no spaces/special chars,
 * joined with `_` when both parts are non-empty.
 */
function composeAutoGroupHandleFromNameAndUser(groupName, userHandleOrFallback) {
  const namePart = alphanumericHandleSegment(groupName);
  const userPart = alphanumericHandleSegment(
    normalizePersonHandle(userHandleOrFallback) || userHandleOrFallback
  );
  if (!namePart && !userPart) return 'group';
  if (!namePart) return userPart;
  if (!userPart) return namePart;
  return `${namePart}_${userPart}`;
}

async function resolveOwnerHandleStringForSlug(ownerEmail) {
  const p = await supabaseProfiles.getProfileByEmail(ownerEmail);
  if (p && p.handle != null && String(p.handle).trim()) {
    return String(p.handle).trim();
  }
  const e = normalizeEmail(ownerEmail);
  if (!e) return '';
  const at = e.indexOf('@');
  return at > 0 ? e.slice(0, at) : e;
}

/**
 * Returns a `handle` not yet used in `groups` or `group_details`.
 * On collision, appends `2`, `3`, … (alphanumeric only).
 */
async function allocateUniqueGroupHandle(supabase, baseHandle) {
  const seed = alphanumericHandleSegment(baseHandle) || 'group';
  for (let i = 0; i < 100; i++) {
    const candidate = i === 0 ? seed : `${seed}${i + 1}`;
    const g = await supabase.from('groups').select('group_name').eq('handle', candidate).maybeSingle();
    if (g.error) {
      const msg = String(g.error.message || '').toLowerCase();
      const missingCol =
        msg.includes('handle') && (msg.includes('does not exist') || g.error.code === '42703');
      if (missingCol) return candidate;
      throw g.error;
    }
    if (g.data) continue;

    const gd = await supabase.from('group_details').select('handle').eq('handle', candidate).maybeSingle();
    if (gd.error) {
      const msg = String(gd.error.message || '').toLowerCase();
      const missingRel =
        (msg.includes('group_details') || msg.includes('schema cache')) &&
        (msg.includes('does not exist') || msg.includes('could not find') || gd.error.code === '42P01');
      if (missingRel) return candidate;
      throw gd.error;
    }
    if (!gd.data) return candidate;
  }
  throw new Error('Could not allocate a unique group handle');
}

/** When `contact_details` has no email, `group_members.member` still needs a value (NOT NULL). */
function placeholderMemberEmailForBlindPersonHandle(person_handle) {
  const ph = normalizePersonHandle(person_handle);
  const safe = ph ? ph.replace(/[^a-z0-9._-]/g, '_') : 'unknown';
  return `blind-${safe}@placeholder.local`;
}

/** Member statuses that give a user active membership in a group. */
const MEMBER_STATUSES = ['member', 'blind member', 'admin'];

/**
 * Returns group_member rows where member = userId AND status IN MEMBER_STATUSES,
 * plus admin_list (all members with status='admin' for that group) and is_admin flag.
 * Members are looked up case-insensitively.
 */
async function listGroupsForUser(userId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeEmail(userId);
  if (!uid) return [];

  // Fetch groups the user belongs to (member, blind member, or admin)
  const { data: memberRows, error: e1 } = await supabase
    .from('group_members')
    .select('*')
    .ilike('member', uid)
    .in('status', MEMBER_STATUSES)
    .order('group_name', { ascending: true });
  if (e1) throw e1;

  const groupNames = [...new Set((memberRows || []).map(r => r.group_name))];

  // For each group, fetch all rows where status = 'admin' to build the admin list
  const adminMap = {};
  // Fetch visibility (and optional handle) from the groups table; group_details may override handle
  const visibilityMap = {};
  /** @type {Record<string, string>} */
  const handleMap = {};
  if (groupNames.length) {
    const [adminResult, groupsResult, gdResult] = await Promise.all([
      supabase
        .from('group_members')
        .select('group_name, member')
        .in('group_name', groupNames)
        .eq('status', 'admin'),
      supabase
        .from('groups')
        .select('group_name, visibility')
        .in('group_name', groupNames),
      supabase
        .from('group_details')
        .select('group_name, handle')
        .in('group_name', groupNames)
    ]);
    if (adminResult.error) throw adminResult.error;
    if (groupsResult.error) throw groupsResult.error;
    if (gdResult.error) {
      const msg = String(gdResult.error.message || '').toLowerCase();
      const missingRel =
        (msg.includes('group_details') || msg.includes('schema cache')) &&
        (msg.includes('does not exist') || msg.includes('could not find') || gdResult.error.code === '42P01');
      if (!missingRel) throw gdResult.error;
    }

    for (const a of (adminResult.data || [])) {
      if (!adminMap[a.group_name]) adminMap[a.group_name] = [];
      adminMap[a.group_name].push(a.member);
    }
    for (const g of (groupsResult.data || [])) {
      visibilityMap[g.group_name] = g.visibility || null;
    }
    for (const r of (gdResult.data || [])) {
      const gn = r.group_name != null ? String(r.group_name).trim() : '';
      const h = r.handle != null ? String(r.handle).trim() : '';
      if (gn && h) handleMap[gn] = h;
    }

    const ghFromGroups = await supabase
      .from('groups')
      .select('group_name, handle')
      .in('group_name', groupNames);
    if (!ghFromGroups.error && ghFromGroups.data) {
      for (const g of ghFromGroups.data) {
        const gn = g.group_name != null ? String(g.group_name).trim() : '';
        const h = g.handle != null ? String(g.handle).trim() : '';
        if (gn && h && !handleMap[gn]) handleMap[gn] = h;
      }
    } else if (ghFromGroups.error) {
      const msg = String(ghFromGroups.error.message || '').toLowerCase();
      const missingCol =
        msg.includes('handle') &&
        (msg.includes('does not exist') || ghFromGroups.error.code === '42703');
      if (!missingCol) throw ghFromGroups.error;
    }
  }

  // Deduplicate by group_name — a user may have both a 'member'/'blind member' and 'admin' row.
  // Keep one row per group, preferring the 'admin' row.
  const seen = {};
  for (const row of (memberRows || [])) {
    const existing = seen[row.group_name];
    if (!existing || row.status === 'admin') {
      seen[row.group_name] = row;
    }
  }

  const seenRows = Object.values(seen);
  /** @type {Record<string, { email?: string, name?: string, handle?: string }>} */
  let profileByEmail = {};
  /** @type {Record<string, string|null>} */
  let photoByHandleKey = {};
  if (supabaseProfiles.isConfigured()) {
    const allAdminEmails = [
      ...new Set(
        seenRows.flatMap(r => adminMap[r.group_name] || []).map(normalizeEmail).filter(Boolean)
      )
    ];
    if (allAdminEmails.length) {
      try {
        const profiles = await supabaseProfiles.getProfilesByEmails(allAdminEmails);
        for (const p of profiles) {
          profileByEmail[normalizeEmail(p.email)] = p;
        }
        const handles = [
          ...new Set(
            (profiles || [])
              .map(p => (p && p.handle ? String(p.handle).trim() : ''))
              .filter(Boolean)
          )
        ];
        const photoResults = await Promise.all(
          handles.map(h => supabaseProfiles.getProfilePhotoUrl(h))
        );
        handles.forEach((h, i) => {
          photoByHandleKey[normalizePersonHandle(h)] = photoResults[i] || null;
        });
      } catch (e) {
        console.warn('listGroupsForUser: admin profile enrichment failed', e);
      }
    }
  }

  return seenRows.map(row => {
    const adminList = adminMap[row.group_name] || [];
    const ghFromMember =
      row.group_handle != null ? String(row.group_handle).trim() : '';
    const handle =
      (row.group_name && handleMap[row.group_name]) || ghFromMember || null;
    const admin_profiles = adminList.map(memberEmail => {
      const ne = normalizeEmail(memberEmail);
      const p = profileByEmail[ne];
      const h = p && p.handle != null ? String(p.handle).trim() : '';
      const phKey = h ? normalizePersonHandle(h) : '';
      const photo_url = phKey ? photoByHandleKey[phKey] ?? null : null;
      let name = '';
      if (p && p.name != null && String(p.name).trim()) {
        name = String(p.name).trim();
      } else {
        const at = ne.indexOf('@');
        name = at > 0 ? ne.slice(0, at) : ne;
      }
      return {
        email: memberEmail,
        name,
        handle: h || null,
        photo_url: photo_url || null
      };
    });
    return {
      ...row,
      is_admin: adminList.map(a => normalizeEmail(a)).includes(uid),
      admin_list: adminList,
      admin_profiles,
      visibility: visibilityMap[row.group_name] || null,
      handle
    };
  });
}

/**
 * Returns group_member rows where member = userId AND status = 'invited'.
 */
async function listInvitesForUser(userId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeEmail(userId);
  if (!uid) return [];

  const { data, error } = await supabase
    .from('group_members')
    .select('*')
    .eq('member', uid)
    .eq('status', 'invited')
    .order('group_name', { ascending: true });
  if (error) throw error;
  return data || [];
}

/**
 * Accept a group invite:  set status = 'member' where id matches and member = invitee.
 * Reject a group invite:  delete the row where group_name + member match the invitee.
 * Only the invitee (member) may respond.
 */
async function respondToGroupInvite(id, userId, action) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeEmail(userId);
  if (action !== 'accept' && action !== 'reject') throw new Error('action must be accept or reject');

  const { data: row, error: selErr } = await supabase
    .from('group_members')
    .select('id, group_name, member, status')
    .eq('id', id)
    .maybeSingle();
  if (selErr) throw selErr;
  if (!row) return false;
  if (normalizeEmail(row.member) !== uid) return false;
  if (row.status !== 'invited') return false;

  if (action === 'accept') {
    const { error } = await supabase
      .from('group_members')
      .update({ status: 'member' })
      .eq('group_name', row.group_name)
      .eq('member', uid);
    if (error) throw error;
  } else {
    const { error } = await supabase
      .from('group_members')
      .delete()
      .eq('group_name', row.group_name)
      .eq('member', uid);
    if (error) throw error;
  }
  return true;
}

/**
 * Creates a new group and its initial members.
 *
 * @param {object} opts
 * @param {string}   opts.group_name
 * @param {string}   opts.visibility       e.g. 'Only me' | 'Members only' | 'Public'
 * @param {string}   opts.owner            email of the creating user (added as admin with person_handle + group_handle)
 * @param {string[]} opts.admins           emails assigned status 'admin'
 * @param {string[]} opts.invited_members  emails assigned status 'invited'
 */
async function createGroup({ group_name, visibility, owner, admins, invited_members }) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');

  const name = (group_name || '').trim();
  if (!name) throw new Error('group_name is required');
  const ownerEmail = normalizeEmail(owner);
  if (!ownerEmail) throw new Error('owner is required');

  const ownerSlugSource = await resolveOwnerHandleStringForSlug(ownerEmail);
  const composedHandle = composeAutoGroupHandleFromNameAndUser(name, ownerSlugSource);
  let storedHandle = await allocateUniqueGroupHandle(supabase, composedHandle);

  const baseRow = { group_name: name, visibility: visibility || null, owner: ownerEmail };
  let { error: groupErr } = await supabase
    .from('groups')
    .insert({ ...baseRow, handle: storedHandle });
  if (groupErr) {
    const msg = String(groupErr.message || '').toLowerCase();
    const missingHandleCol =
      msg.includes('handle') && (msg.includes('does not exist') || groupErr.code === '42703');
    if (missingHandleCol) {
      storedHandle = null;
      const r2 = await supabase.from('groups').insert(baseRow);
      if (r2.error) throw r2.error;
    } else {
      throw groupErr;
    }
  }

  if (storedHandle) {
    const gdi = await supabase
      .from('group_details')
      .insert({ handle: storedHandle, group_name: name });
    if (gdi.error) {
      const msg = String(gdi.error.message || '').toLowerCase();
      const missingRel =
        (msg.includes('group_details') || msg.includes('schema cache')) &&
        (msg.includes('does not exist') || msg.includes('could not find') || gdi.error.code === '42P01');
      const dup = gdi.error.code === '23505';
      if (!missingRel && !dup) throw gdi.error;
    }
  }

  // Build member rows — deduplicate by normalised email
  const memberRowMap = {};

  // Admins (always 'admin' regardless of visibility)
  for (const email of (admins || [])) {
    const e = normalizeEmail(email);
    if (e) memberRowMap[e] = { group_name: name, member: e, status: 'admin' };
  }

  // 'Only me' groups add people directly as members (no invite step).
  // All other visibility types send an invitation first.
  const newMemberStatus = visibility === 'Only me' ? 'member' : 'invited';

  for (const email of (invited_members || [])) {
    const e = normalizeEmail(email);
    if (e && !memberRowMap[e]) {
      memberRowMap[e] = { group_name: name, member: e, status: newMemberStatus };
    }
  }

  const ownerPersonHandle =
    normalizePersonHandle(ownerSlugSource) ||
    alphanumericHandleSegment(ownerSlugSource) ||
    null;
  const ownerGroupHandleNorm = storedHandle
    ? normalizePersonHandle(storedHandle)
    : null;

  memberRowMap[ownerEmail] = {
    group_name: name,
    member: ownerEmail,
    status: 'admin',
    ...(ownerPersonHandle ? { person_handle: ownerPersonHandle } : {}),
    ...(ownerGroupHandleNorm ? { group_handle: ownerGroupHandleNorm } : {})
  };

  const memberRows = Object.values(memberRowMap);
  if (memberRows.length) {
    const { error: membersErr } = await supabase.from('group_members').insert(memberRows);
    if (membersErr) throw membersErr;
  }

  return { group_name: name, handle: storedHandle || null };
}

/**
 * Returns full details for a single group: group row + admins + members + invited_members.
 */
async function getGroupDetails(groupName) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');

  const ALL_STATUSES = [...MEMBER_STATUSES, 'invited'];

  const [groupResult, membersResult] = await Promise.all([
    supabase.from('groups').select('group_name, visibility, owner').eq('group_name', groupName).maybeSingle(),
    supabase.from('group_members').select('member, status').eq('group_name', groupName).in('status', ALL_STATUSES)
  ]);
  if (groupResult.error) throw groupResult.error;
  if (membersResult.error) throw membersResult.error;
  if (!groupResult.data) return null;

  const rows = membersResult.data || [];
  const admins = rows.filter(r => r.status === 'admin').map(r => r.member);
  const members = rows.filter(r => r.status === 'member' || r.status === 'blind member').map(r => r.member);
  const invited_members = rows.filter(r => r.status === 'invited').map(r => r.member);

  return { ...groupResult.data, admins, members, invited_members };
}

/**
 * Updates an existing group's visibility, admins, members, and invited_members.
 * Replaces all admin / member / blind member / invited rows entirely.
 */
async function updateGroup({ group_name, visibility, admins, members, invited_members, owner }) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');

  const name = (group_name || '').trim();
  if (!name) throw new Error('group_name is required');

  // Update the groups table row
  const update = {};
  if (visibility !== undefined) update.visibility = visibility;
  if (Object.keys(update).length) {
    const { error: upErr } = await supabase.from('groups').update(update).eq('group_name', name);
    if (upErr) throw upErr;
  }

  // 'Only me' groups use 'blind member' status for confirmed members
  const memberStatus = visibility === 'Only me' ? 'blind member' : 'member';

  // Replace all non-invited and invited rows
  const { error: delErr } = await supabase
    .from('group_members')
    .delete()
    .eq('group_name', name)
    .in('status', ['admin', 'member', 'blind member', 'invited']);
  if (delErr) throw delErr;

  const memberRowMap = {};

  // Admins
  for (const email of (admins || [])) {
    const e = normalizeEmail(email);
    if (e) memberRowMap[e] = { group_name: name, member: e, status: 'admin' };
  }

  // Confirmed members (don't downgrade an admin)
  for (const email of (members || [])) {
    const e = normalizeEmail(email);
    if (e && !memberRowMap[e]) memberRowMap[e] = { group_name: name, member: e, status: memberStatus };
  }

  // Invited members (don't downgrade an admin or confirmed member)
  for (const email of (invited_members || [])) {
    const e = normalizeEmail(email);
    if (e && !memberRowMap[e]) memberRowMap[e] = { group_name: name, member: e, status: 'invited' };
  }

  // Ensure owner always stays as a confirmed member
  const ownerEmail = normalizeEmail(owner);
  if (ownerEmail && !memberRowMap[ownerEmail]) {
    memberRowMap[ownerEmail] = { group_name: name, member: ownerEmail, status: memberStatus };
  }

  const rows = Object.values(memberRowMap);
  if (rows.length) {
    const { error: insErr } = await supabase.from('group_members').insert(rows);
    if (insErr) throw insErr;
  }
  return { group_name: name };
}

/**
 * Deletes a group and all its group_members rows.
 * Only the group owner or an admin may delete.
 * Returns { ok: true } or throws an error with a user-facing message.
 */
async function deleteGroup(groupName, userId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeEmail(userId);

  // Check ownership
  const { data: groupRow, error: gErr } = await supabase
    .from('groups').select('owner').eq('group_name', groupName).maybeSingle();
  if (gErr) throw gErr;
  if (!groupRow) throw Object.assign(new Error('Group not found'), { status: 404 });

  const isOwner = normalizeEmail(groupRow.owner) === uid;

  // Check admin status
  const { data: adminRow, error: aErr } = await supabase
    .from('group_members')
    .select('id')
    .eq('group_name', groupName)
    .ilike('member', uid)
    .eq('status', 'admin')
    .maybeSingle();
  if (aErr) throw aErr;

  if (!isOwner && !adminRow) {
    throw Object.assign(new Error('Only group admins can delete group'), { status: 403 });
  }

  // Delete all group_members first, then the group row
  const { error: delMembersErr } = await supabase.from('group_members').delete().eq('group_name', groupName);
  if (delMembersErr) throw delMembersErr;
  const { error: delGroupErr } = await supabase.from('groups').delete().eq('group_name', groupName);
  if (delGroupErr) throw delGroupErr;

  return { ok: true };
}

/**
 * Removes the user from a group's group_members rows (any status).
 */
async function leaveGroup(groupName, userId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeEmail(userId);

  const { error } = await supabase
    .from('group_members')
    .delete()
    .eq('group_name', groupName)
    .ilike('member', uid);
  if (error) throw error;
  return { ok: true };
}

/**
 * Builds a connections map for the logged-in user.
 *
 * "Relevant groups" are those where:
 *   a) the user is an active member (member/blind member/admin) AND the group
 *      visibility is "Members only", OR
 *   b) the user is the owner of the group (any visibility).
 *
 * Returns an object keyed by lowercase member email:
 *   { "other@example.com": ["Group A", "Group B"], ... }
 *
 * The logged-in user themselves are excluded from the result.
 */
function isMembersOnlyVisibility(visibility) {
  if (visibility == null) return false;
  return String(visibility).trim().toLowerCase() === 'members only';
}

async function getConnectionsForUser(userId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeEmail(userId);
  if (!uid) return {};

  // 1) Groups the user actively belongs to (member / blind member / admin)
  const { data: userMemberRows, error: e1 } = await supabase
    .from('group_members')
    .select('group_name')
    .ilike('member', uid)
    .in('status', MEMBER_STATUSES);
  if (e1) throw e1;

  const userGroupNames = [...new Set((userMemberRows || []).map(r => r.group_name))];

  // 2) Groups the user owns (always relevant, even if group row was missing from step 3 before)
  const { data: ownedRows, error: eOwned } = await supabase
    .from('groups')
    .select('group_name')
    .ilike('owner', uid);
  if (eOwned) throw eOwned;
  const ownedGroupNames = [...new Set((ownedRows || []).map(r => r.group_name))];

  // 3) Visibility for groups the user is a member of — pick "Members only"
  let memberOnlyGroupNames = [];
  if (userGroupNames.length) {
    const { data: groupRows, error: e2 } = await supabase
      .from('groups')
      .select('group_name, visibility')
      .in('group_name', userGroupNames);
    if (e2) throw e2;
    memberOnlyGroupNames = (groupRows || [])
      .filter(g => isMembersOnlyVisibility(g.visibility))
      .map(g => g.group_name);
  }

  // Union: owned groups + members-only groups user belongs to
  const relevantGroupNames = [...new Set([...ownedGroupNames, ...memberOnlyGroupNames])];
  if (!relevantGroupNames.length) return {};

  // 4) All active members of those groups
  const { data: allMemberRows, error: e3 } = await supabase
    .from('group_members')
    .select('group_name, member')
    .in('group_name', relevantGroupNames)
    .in('status', MEMBER_STATUSES);
  if (e3) throw e3;

  // Canonical group rows — only use real `groups.group_name` values (never owner email as a "group" tag)
  const { data: groupMetaRows, error: eMeta } = await supabase
    .from('groups')
    .select('group_name, owner')
    .in('group_name', relevantGroupNames);
  if (eMeta) throw eMeta;
  const groupMetaByNorm = new Map();
  for (const g of groupMetaRows || []) {
    const key = normalizeEmail(g.group_name);
    if (!key) continue;
    groupMetaByNorm.set(key, g);
  }

  // Build map: normalised member email → [group names from `groups` table]
  const connectionsMap = {};
  for (const row of (allMemberRows || [])) {
    const memberEmail = normalizeEmail(row.member);
    if (memberEmail === uid) continue; // exclude self

    const gnRaw = row.group_name != null ? String(row.group_name).trim() : '';
    const gnNorm = normalizeEmail(gnRaw);
    if (!gnNorm) continue;

    const meta = groupMetaByNorm.get(gnNorm);
    if (!meta) continue; // orphan group_members row with no matching groups row

    // Skip misconfigured rows where group_name equals owner (shows email as a fake "group")
    if (normalizeEmail(meta.owner) === gnNorm) continue;

    const displayName = meta.group_name != null ? String(meta.group_name).trim() : gnRaw;
    if (!displayName) continue;

    if (!connectionsMap[memberEmail]) connectionsMap[memberEmail] = [];
    if (!connectionsMap[memberEmail].includes(displayName)) {
      connectionsMap[memberEmail].push(displayName);
    }
  }
  return connectionsMap;
}

/**
 * All rows from `groups` where owner matches userId (case-insensitive), ordered by group_name.
 */
async function listGroupsOwnedByUser(userId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeEmail(userId);
  if (!uid) return [];

  const { data, error } = await supabase
    .from('groups')
    .select('group_name, visibility')
    .ilike('owner', uid)
    .order('group_name', { ascending: true });
  if (error) throw error;
  return data || [];
}

/**
 * Owner invites a member to their group (inserts group_members with status invited).
 * Verifies userId is the group owner.
 */
async function inviteMemberAsOwner({ group_name, member, ownerUserId }) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeEmail(ownerUserId);
  const gn = (group_name || '').trim();
  const mem = normalizeEmail(member);
  if (!gn || !mem) throw new Error('group_name and member are required');

  const { data: g, error: gErr } = await supabase
    .from('groups')
    .select('owner')
    .eq('group_name', gn)
    .maybeSingle();
  if (gErr) throw gErr;
  if (!g) throw Object.assign(new Error('Group not found'), { status: 404 });
  if (normalizeEmail(g.owner) !== uid) {
    throw Object.assign(new Error('Only the group owner can invite from here'), { status: 403 });
  }

  const { error: insErr } = await supabase
    .from('group_members')
    .insert({ group_name: gn, member: mem, status: 'invited' });
  if (insErr) {
    if (insErr.code === '23505') {
      throw Object.assign(new Error('That person is already in this group or has a pending invite'), { status: 409 });
    }
    throw insErr;
  }
  return { ok: true };
}

/**
 * Returns the email addresses of all 'member' and 'blind member' rows for a group.
 */
async function getGroupMembers(groupName) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const { data, error } = await supabase
    .from('group_members')
    .select('member')
    .eq('group_name', groupName)
    .in('status', ['member', 'blind member']);
  if (error) throw error;
  return (data || []).map(r => r.member);
}

/**
 * Throws if userId is not the group owner or an admin in group_members.
 */
async function assertUserCanManageGroup(groupName, userId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeEmail(userId);
  const gn = (groupName || '').trim();
  if (!gn || !uid) {
    throw Object.assign(new Error('group_name and user are required'), { status: 400 });
  }

  const { data: g, error: gErr } = await supabase
    .from('groups')
    .select('owner')
    .eq('group_name', gn)
    .maybeSingle();
  if (gErr) throw gErr;
  if (!g) throw Object.assign(new Error('Group not found'), { status: 404 });
  if (normalizeEmail(g.owner) === uid) return;

  const { data: adm, error: aErr } = await supabase
    .from('group_members')
    .select('id')
    .eq('group_name', gn)
    .ilike('member', uid)
    .eq('status', 'admin')
    .maybeSingle();
  if (aErr) throw aErr;
  if (!adm) {
    throw Object.assign(new Error('Only group owners and admins can do this'), { status: 403 });
  }
}

/**
 * Groups where the user is the owner (groups.owner) or has status admin in group_members.
 */
async function listGroupsWhereUserCanManageMembers(userId) {
  const uid = normalizeEmail(userId);
  if (!uid) return [];

  const owned = await listGroupsOwnedByUser(userId);
  const names = new Set((owned || []).map(g => g.group_name));

  const userGroups = await listGroupsForUser(userId);
  for (const row of userGroups || []) {
    if (row.is_admin) names.add(row.group_name);
  }

  return [...names]
    .sort((a, b) => a.localeCompare(b, undefined, { sensitivity: 'base' }))
    .map(group_name => ({ group_name }));
}

const MEMBERSHIP_LIST_STATUSES = [...MEMBER_STATUSES, 'invited'];

/**
 * All group_members rows whose person_handle matches (for contact public handle).
 * Each row includes can_remove if viewerUserId may manage that group.
 */
async function getMembershipsByPersonHandleForViewer(person_handle, viewerUserId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const ph = normalizePersonHandle(person_handle);
  if (!ph) return [];

  const { data: rows, error } = await supabase
    .from('group_members')
    .select('id, group_name, status, member, person_handle')
    .ilike('person_handle', ph)
    .in('status', MEMBERSHIP_LIST_STATUSES)
    .order('group_name', { ascending: true });
  if (error) throw error;

  const out = [];
  for (const r of rows || []) {
    let can_remove = false;
    try {
      await assertUserCanManageGroup(r.group_name, viewerUserId);
      can_remove = true;
    } catch (e) {
      can_remove = false;
    }
    out.push({
      id: r.id,
      group_name: r.group_name,
      status: r.status,
      can_remove
    });
  }
  return out;
}

async function removeMembershipByPersonHandle({ group_name, person_handle, actorUserId }) {
  await assertUserCanManageGroup(group_name, actorUserId);
  const supabase = getClient();
  const ph = normalizePersonHandle(person_handle);
  if (!ph) throw new Error('person_handle is required');
  const { error } = await supabase
    .from('group_members')
    .delete()
    .eq('group_name', (group_name || '').trim())
    .ilike('person_handle', ph);
  if (error) throw error;
  return { ok: true };
}

/**
 * Deletes the `group_members` row where `group_handle` matches the URL group and `person_handle` matches.
 * Viewer must be group owner or admin. Falls back to `group_name` + `person_handle` if `group_handle` column is absent.
 */
async function removeGroupMemberByGroupHandleAndPersonHandle({
  groupHandleRaw,
  person_handle,
  actorUserId
}) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');

  const groupRow = await getGroupRowByHandle(groupHandleRaw);
  const gn = groupRow && groupRow.group_name != null ? String(groupRow.group_name).trim() : '';
  if (!gn) {
    throw Object.assign(new Error('Group not found'), { status: 404 });
  }
  await assertUserCanManageGroup(gn, actorUserId);

  const ph = normalizePersonHandle(person_handle);
  if (!ph) throw new Error('person_handle is required');

  const candidates = groupHandleCandidates(groupHandleRaw);

  const r1 = await supabase
    .from('group_members')
    .delete()
    .in('group_handle', candidates)
    .ilike('person_handle', ph)
    .select('id');

  if (r1.error) {
    const msg = String(r1.error.message || '').toLowerCase();
    const missingCol =
      msg.includes('group_handle') && (msg.includes('does not exist') || r1.error.code === '42703');
    if (!missingCol) throw r1.error;
  } else if (r1.data && r1.data.length) {
    return { ok: true };
  }

  const r2 = await supabase
    .from('group_members')
    .delete()
    .eq('group_name', gn)
    .ilike('person_handle', ph)
    .select('id');
  if (r2.error) throw r2.error;
  if (!r2.data || !r2.data.length) {
    throw Object.assign(new Error('Membership not found'), { status: 404 });
  }
  return { ok: true };
}

/**
 * Invite a member by email and store person_handle on the row (owner or admin may invite).
 */
async function inviteMemberWithPersonHandle({
  group_name,
  memberEmail,
  person_handle,
  actorUserId,
  groupHandleRaw,
  membershipStatus
}) {
  await assertUserCanManageGroup(group_name, actorUserId);
  const supabase = getClient();
  const gn = (group_name || '').trim();
  const ph = normalizePersonHandle(person_handle);
  const rawStatus =
    membershipStatus != null && String(membershipStatus).trim()
      ? String(membershipStatus).trim().toLowerCase()
      : 'invited';
  if (rawStatus !== 'invited' && rawStatus !== 'blind member') {
    throw Object.assign(
      new Error('membership_status must be invited or blind member'),
      { status: 400 }
    );
  }
  const statusForRow = rawStatus === 'blind member' ? 'blind member' : 'invited';

  let mem = normalizeEmail(memberEmail);
  if (statusForRow === 'blind member' && !mem) {
    mem = placeholderMemberEmailForBlindPersonHandle(person_handle);
  }
  if (!gn || !mem) throw new Error('group_name and member email are required');

  let groupHandleForRow = null;
  if (groupHandleRaw != null && String(groupHandleRaw).trim()) {
    const groupRow = await getGroupRowByHandle(groupHandleRaw);
    const rowGn =
      groupRow && groupRow.group_name != null
        ? String(groupRow.group_name).trim()
        : '';
    if (!groupRow || !rowGn || rowGn.toLowerCase() !== gn.toLowerCase()) {
      throw Object.assign(new Error('group_handle does not match group_name'), {
        status: 400
      });
    }
    const stored =
      groupRow.handle != null && String(groupRow.handle).trim()
        ? String(groupRow.handle).trim()
        : String(groupHandleRaw).trim();
    groupHandleForRow = normalizePersonHandle(stored) || normalizePersonHandle(groupHandleRaw);
  }

  const insertPayload = {
    group_name: gn,
    member: mem,
    status: statusForRow,
    person_handle: ph || null,
    ...(groupHandleForRow ? { group_handle: groupHandleForRow } : {})
  };

  const { error: insErr } = await supabase.from('group_members').insert(insertPayload);
  if (insErr) {
    if (insErr.code === '23505') {
      throw Object.assign(
        new Error('That person is already in this group or has a pending invite'),
        { status: 409 }
      );
    }
    throw insErr;
  }
  return { ok: true };
}

/**
 * Normalized handle variants from a URL segment.
 * Includes lowercase/no-@ forms so DB rows match `normalizePersonHandle` (same as stored handles).
 */
function groupHandleCandidates(raw) {
  const q = String(raw || '').trim();
  if (!q) return [];
  const noAt = q.replace(/^@+/, '');
  const withAt = '@' + noAt;
  const norm = normalizePersonHandle(q);
  const normWithAt = norm ? '@' + norm : '';
  return [...new Set([q, noAt, withAt, norm, normWithAt].filter(Boolean))];
}

/**
 * One row from `group_details` where `handle` matches the URL (typically stored without `@`, e.g. `collegefriends_johnpicasso`).
 * Falls back to legacy `groups` when `group_details` is missing or has no row.
 */
async function getGroupRowByHandle(handleRaw) {
  const supabase = getClient();
  if (!supabase) return null;
  const candidates = groupHandleCandidates(handleRaw);
  if (!candidates.length) return null;

  const rGd = await supabase.from('group_details').select('*').in('handle', candidates).limit(1);
  if (rGd.error) {
    const msg = String(rGd.error.message || '').toLowerCase();
    const missingRel =
      (msg.includes('group_details') || msg.includes('schema cache')) &&
      (msg.includes('does not exist') || msg.includes('could not find') || rGd.error.code === '42P01');
    if (!missingRel) throw rGd.error;
  } else if (rGd.data && rGd.data.length) {
    return rGd.data[0];
  }

  const r1 = await supabase.from('groups').select('*').in('handle', candidates).limit(1);
  if (r1.error) {
    const msg = String(r1.error.message || '').toLowerCase();
    const missingCol = msg.includes('handle') && (msg.includes('does not exist') || r1.error.code === '42703');
    if (!missingCol) throw r1.error;
  } else if (r1.data && r1.data.length) {
    return r1.data[0];
  }

  const r2 = await supabase.from('groups').select('*').in('group_name', candidates).limit(1);
  if (r2.error) throw r2.error;
  if (r2.data && r2.data.length) return r2.data[0];

  // Infer group_name from group_members when handle exists on membership rows but not on groups/group_details yet
  const gm = await supabase
    .from('group_members')
    .select('group_name')
    .in('group_handle', candidates)
    .limit(1);
  if (gm.error) {
    const msg = String(gm.error.message || '').toLowerCase();
    const missingCol =
      msg.includes('group_handle') && (msg.includes('does not exist') || gm.error.code === '42703');
    if (!missingCol) throw gm.error;
  } else if (gm.data && gm.data.length) {
    const gn = gm.data[0].group_name != null ? String(gm.data[0].group_name).trim() : '';
    if (gn) {
      const rGd2 = await supabase.from('group_details').select('*').eq('group_name', gn).limit(1);
      if (!rGd2.error && rGd2.data && rGd2.data.length) return rGd2.data[0];
      if (rGd2.error) {
        const msg = String(rGd2.error.message || '').toLowerCase();
        const missingRel =
          (msg.includes('group_details') || msg.includes('schema cache')) &&
          (msg.includes('does not exist') || msg.includes('could not find') || rGd2.error.code === '42P01');
        if (!missingRel) throw rGd2.error;
      }
      const rG = await supabase.from('groups').select('*').eq('group_name', gn).limit(1);
      if (rG.error) throw rG.error;
      if (rG.data && rG.data.length) return rG.data[0];
      return {
        group_name: gn,
        handle: normalizePersonHandle(handleRaw) || null
      };
    }
  }

  return null;
}

/**
 * All `group_members` for this group handle (`group_handle`), else by resolved `group_name`.
 * When `viewerUserId` is set, rows may include `contact_name` from `contact_details` (viewer's address book).
 * Rows without a contact match get `profile_name` from `profiles.handle` = `person_handle`.
 * `display_name` / `display_status` append `, contact` or `, friend` to the stored `status` for the UI.
 */
async function listMembersRowsByGroupHandle(handleRaw, viewerUserId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const groupRow = await getGroupRowByHandle(handleRaw);
  const candidates = groupHandleCandidates(handleRaw);

  const r1 = await supabase
    .from('group_members')
    .select('id, member, status, person_handle, group_name, group_handle')
    .in('group_handle', candidates)
    .order('member', { ascending: true });

  let rows = [];
  if (!r1.error && r1.data && r1.data.length) {
    rows = r1.data;
  } else if (r1.error) {
    const msg = String(r1.error.message || '').toLowerCase();
    const missingCol =
      msg.includes('group_handle') && (msg.includes('does not exist') || r1.error.code === '42703');
    if (!missingCol) throw r1.error;
  }

  if (!rows.length && groupRow && groupRow.group_name) {
    const r2 = await supabase
      .from('group_members')
      .select('id, member, status, person_handle, group_name, group_handle')
      .eq('group_name', groupRow.group_name)
      .order('member', { ascending: true });
    if (r2.error) throw r2.error;
    rows = r2.data || [];
  }

  const uid = normalizeEmail(viewerUserId);
  if (rows.length && supabaseProfiles.isConfigured()) {
    try {
      if (uid) {
        const profile = await supabaseProfiles.getProfileByEmail(uid);
        const oh =
          profile && profile.handle != null ? String(profile.handle).trim() : '';
        if (oh) {
          rows = await supabaseProfiles.enrichGroupMemberRowsWithContactNames(oh, rows);
        }
      }
      rows = await supabaseProfiles.enrichGroupMemberRowsWithProfileNames(rows);
      rows = supabaseProfiles.attachGroupMemberDisplayFields(rows);
    } catch (e) {
      console.warn('enrich group member display:', e.message || e);
    }
  }

  return rows;
}

module.exports = {
  isConfigured,
  listGroupsForUser,
  listInvitesForUser,
  respondToGroupInvite,
  createGroup,
  getGroupDetails,
  updateGroup,
  deleteGroup,
  leaveGroup,
  getGroupMembers,
  getConnectionsForUser,
  listGroupsOwnedByUser,
  inviteMemberAsOwner,
  normalizePersonHandle,
  listGroupsWhereUserCanManageMembers,
  getMembershipsByPersonHandleForViewer,
  removeMembershipByPersonHandle,
  removeGroupMemberByGroupHandleAndPersonHandle,
  inviteMemberWithPersonHandle,
  groupHandleCandidates,
  getGroupRowByHandle,
  listMembersRowsByGroupHandle
};
