/**
 * Groups in Supabase.
 *
 * Table: `group_members`  — id, group_name, member (email), status ('invited'|'member'|'admin'), person_handle (optional)
 *
 * Admins are rows in group_members where status = 'admin'.
 *
 * SQL (run in Supabase if missing):
 *
 *   create table if not exists public.group_members (
 *     id bigint generated by default as identity primary key,
 *     group_name text not null,
 *     member text not null,
 *     status text not null default 'invited'
 *   );
 *   alter table public.group_members add column if not exists person_handle text;
 */

let client = null;

function isConfigured() {
  return !!(process.env.SUPABASE_URL && process.env.SUPABASE_SERVICE_ROLE_KEY);
}

function getClient() {
  if (client) return client;
  if (!isConfigured()) return null;
  const { createClient } = require('@supabase/supabase-js');
  client = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
  return client;
}

function normalizeEmail(s) {
  return s != null ? String(s).trim().toLowerCase() : '';
}

/** Normalized public handle (no @), lowercased — matches `contact_details.contact_handle` / `group_members.person_handle`. */
function normalizePersonHandle(s) {
  return s != null ? String(s).trim().replace(/^@+/, '').toLowerCase() : '';
}

/** Member statuses that give a user active membership in a group. */
const MEMBER_STATUSES = ['member', 'blind member', 'admin'];

/**
 * Returns group_member rows where member = userId AND status IN MEMBER_STATUSES,
 * plus admin_list (all members with status='admin' for that group) and is_admin flag.
 * Members are looked up case-insensitively.
 */
async function listGroupsForUser(userId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeEmail(userId);
  if (!uid) return [];

  // Fetch groups the user belongs to (member, blind member, or admin)
  const { data: memberRows, error: e1 } = await supabase
    .from('group_members')
    .select('*')
    .ilike('member', uid)
    .in('status', MEMBER_STATUSES)
    .order('group_name', { ascending: true });
  if (e1) throw e1;

  const groupNames = [...new Set((memberRows || []).map(r => r.group_name))];

  // For each group, fetch all rows where status = 'admin' to build the admin list
  const adminMap = {};
  // Fetch visibility from the groups table
  const visibilityMap = {};
  if (groupNames.length) {
    const [adminResult, groupsResult] = await Promise.all([
      supabase
        .from('group_members')
        .select('group_name, member')
        .in('group_name', groupNames)
        .eq('status', 'admin'),
      supabase
        .from('groups')
        .select('group_name, visibility')
        .in('group_name', groupNames)
    ]);
    if (adminResult.error) throw adminResult.error;
    if (groupsResult.error) throw groupsResult.error;

    for (const a of (adminResult.data || [])) {
      if (!adminMap[a.group_name]) adminMap[a.group_name] = [];
      adminMap[a.group_name].push(a.member);
    }
    for (const g of (groupsResult.data || [])) {
      visibilityMap[g.group_name] = g.visibility || null;
    }
  }

  // Deduplicate by group_name — a user may have both a 'member'/'blind member' and 'admin' row.
  // Keep one row per group, preferring the 'admin' row.
  const seen = {};
  for (const row of (memberRows || [])) {
    const existing = seen[row.group_name];
    if (!existing || row.status === 'admin') {
      seen[row.group_name] = row;
    }
  }

  return Object.values(seen).map(row => {
    const adminList = adminMap[row.group_name] || [];
    return {
      ...row,
      is_admin: adminList.map(a => normalizeEmail(a)).includes(uid),
      admin_list: adminList,
      visibility: visibilityMap[row.group_name] || null
    };
  });
}

/**
 * Returns group_member rows where member = userId AND status = 'invited'.
 */
async function listInvitesForUser(userId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeEmail(userId);
  if (!uid) return [];

  const { data, error } = await supabase
    .from('group_members')
    .select('*')
    .eq('member', uid)
    .eq('status', 'invited')
    .order('group_name', { ascending: true });
  if (error) throw error;
  return data || [];
}

/**
 * Accept a group invite:  set status = 'member' where id matches and member = invitee.
 * Reject a group invite:  delete the row where group_name + member match the invitee.
 * Only the invitee (member) may respond.
 */
async function respondToGroupInvite(id, userId, action) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeEmail(userId);
  if (action !== 'accept' && action !== 'reject') throw new Error('action must be accept or reject');

  const { data: row, error: selErr } = await supabase
    .from('group_members')
    .select('id, group_name, member, status')
    .eq('id', id)
    .maybeSingle();
  if (selErr) throw selErr;
  if (!row) return false;
  if (normalizeEmail(row.member) !== uid) return false;
  if (row.status !== 'invited') return false;

  if (action === 'accept') {
    const { error } = await supabase
      .from('group_members')
      .update({ status: 'member' })
      .eq('group_name', row.group_name)
      .eq('member', uid);
    if (error) throw error;
  } else {
    const { error } = await supabase
      .from('group_members')
      .delete()
      .eq('group_name', row.group_name)
      .eq('member', uid);
    if (error) throw error;
  }
  return true;
}

/**
 * Creates a new group and its initial members.
 *
 * @param {object} opts
 * @param {string}   opts.group_name
 * @param {string}   opts.visibility       e.g. 'Only me' | 'Members only' | 'Public'
 * @param {string}   opts.owner            email of the creating user (auto-added as 'member')
 * @param {string[]} opts.admins           emails assigned status 'admin'
 * @param {string[]} opts.invited_members  emails assigned status 'invited'
 */
async function createGroup({ group_name, visibility, owner, admins, invited_members }) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');

  const name = (group_name || '').trim();
  if (!name) throw new Error('group_name is required');
  const ownerEmail = normalizeEmail(owner);
  if (!ownerEmail) throw new Error('owner is required');

  // Insert the group row
  const { error: groupErr } = await supabase
    .from('groups')
    .insert({ group_name: name, visibility: visibility || null, owner: ownerEmail });
  if (groupErr) throw groupErr;

  // Build member rows — deduplicate by normalised email
  const memberRowMap = {};

  // Admins (always 'admin' regardless of visibility)
  for (const email of (admins || [])) {
    const e = normalizeEmail(email);
    if (e) memberRowMap[e] = { group_name: name, member: e, status: 'admin' };
  }

  // 'Only me' groups add people directly as members (no invite step).
  // All other visibility types send an invitation first.
  const newMemberStatus = visibility === 'Only me' ? 'member' : 'invited';

  for (const email of (invited_members || [])) {
    const e = normalizeEmail(email);
    if (e && !memberRowMap[e]) {
      memberRowMap[e] = { group_name: name, member: e, status: newMemberStatus };
    }
  }

  // Owner is a full member immediately (they created the group)
  if (!memberRowMap[ownerEmail]) {
    memberRowMap[ownerEmail] = { group_name: name, member: ownerEmail, status: 'member' };
  }

  const memberRows = Object.values(memberRowMap);
  if (memberRows.length) {
    const { error: membersErr } = await supabase.from('group_members').insert(memberRows);
    if (membersErr) throw membersErr;
  }

  return { group_name: name };
}

/**
 * Returns full details for a single group: group row + admins + members + invited_members.
 */
async function getGroupDetails(groupName) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');

  const ALL_STATUSES = [...MEMBER_STATUSES, 'invited'];

  const [groupResult, membersResult] = await Promise.all([
    supabase.from('groups').select('group_name, visibility, owner').eq('group_name', groupName).maybeSingle(),
    supabase.from('group_members').select('member, status').eq('group_name', groupName).in('status', ALL_STATUSES)
  ]);
  if (groupResult.error) throw groupResult.error;
  if (membersResult.error) throw membersResult.error;
  if (!groupResult.data) return null;

  const rows = membersResult.data || [];
  const admins = rows.filter(r => r.status === 'admin').map(r => r.member);
  const members = rows.filter(r => r.status === 'member' || r.status === 'blind member').map(r => r.member);
  const invited_members = rows.filter(r => r.status === 'invited').map(r => r.member);

  return { ...groupResult.data, admins, members, invited_members };
}

/**
 * Updates an existing group's visibility, admins, members, and invited_members.
 * Replaces all admin / member / blind member / invited rows entirely.
 */
async function updateGroup({ group_name, visibility, admins, members, invited_members, owner }) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');

  const name = (group_name || '').trim();
  if (!name) throw new Error('group_name is required');

  // Update the groups table row
  const update = {};
  if (visibility !== undefined) update.visibility = visibility;
  if (Object.keys(update).length) {
    const { error: upErr } = await supabase.from('groups').update(update).eq('group_name', name);
    if (upErr) throw upErr;
  }

  // 'Only me' groups use 'blind member' status for confirmed members
  const memberStatus = visibility === 'Only me' ? 'blind member' : 'member';

  // Replace all non-invited and invited rows
  const { error: delErr } = await supabase
    .from('group_members')
    .delete()
    .eq('group_name', name)
    .in('status', ['admin', 'member', 'blind member', 'invited']);
  if (delErr) throw delErr;

  const memberRowMap = {};

  // Admins
  for (const email of (admins || [])) {
    const e = normalizeEmail(email);
    if (e) memberRowMap[e] = { group_name: name, member: e, status: 'admin' };
  }

  // Confirmed members (don't downgrade an admin)
  for (const email of (members || [])) {
    const e = normalizeEmail(email);
    if (e && !memberRowMap[e]) memberRowMap[e] = { group_name: name, member: e, status: memberStatus };
  }

  // Invited members (don't downgrade an admin or confirmed member)
  for (const email of (invited_members || [])) {
    const e = normalizeEmail(email);
    if (e && !memberRowMap[e]) memberRowMap[e] = { group_name: name, member: e, status: 'invited' };
  }

  // Ensure owner always stays as a confirmed member
  const ownerEmail = normalizeEmail(owner);
  if (ownerEmail && !memberRowMap[ownerEmail]) {
    memberRowMap[ownerEmail] = { group_name: name, member: ownerEmail, status: memberStatus };
  }

  const rows = Object.values(memberRowMap);
  if (rows.length) {
    const { error: insErr } = await supabase.from('group_members').insert(rows);
    if (insErr) throw insErr;
  }
  return { group_name: name };
}

/**
 * Deletes a group and all its group_members rows.
 * Only the group owner or an admin may delete.
 * Returns { ok: true } or throws an error with a user-facing message.
 */
async function deleteGroup(groupName, userId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeEmail(userId);

  // Check ownership
  const { data: groupRow, error: gErr } = await supabase
    .from('groups').select('owner').eq('group_name', groupName).maybeSingle();
  if (gErr) throw gErr;
  if (!groupRow) throw Object.assign(new Error('Group not found'), { status: 404 });

  const isOwner = normalizeEmail(groupRow.owner) === uid;

  // Check admin status
  const { data: adminRow, error: aErr } = await supabase
    .from('group_members')
    .select('id')
    .eq('group_name', groupName)
    .ilike('member', uid)
    .eq('status', 'admin')
    .maybeSingle();
  if (aErr) throw aErr;

  if (!isOwner && !adminRow) {
    throw Object.assign(new Error('Only group admins can delete group'), { status: 403 });
  }

  // Delete all group_members first, then the group row
  const { error: delMembersErr } = await supabase.from('group_members').delete().eq('group_name', groupName);
  if (delMembersErr) throw delMembersErr;
  const { error: delGroupErr } = await supabase.from('groups').delete().eq('group_name', groupName);
  if (delGroupErr) throw delGroupErr;

  return { ok: true };
}

/**
 * Removes the user from a group's group_members rows (any status).
 */
async function leaveGroup(groupName, userId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeEmail(userId);

  const { error } = await supabase
    .from('group_members')
    .delete()
    .eq('group_name', groupName)
    .ilike('member', uid);
  if (error) throw error;
  return { ok: true };
}

/**
 * Builds a connections map for the logged-in user.
 *
 * "Relevant groups" are those where:
 *   a) the user is an active member (member/blind member/admin) AND the group
 *      visibility is "Members only", OR
 *   b) the user is the owner of the group (any visibility).
 *
 * Returns an object keyed by lowercase member email:
 *   { "other@example.com": ["Group A", "Group B"], ... }
 *
 * The logged-in user themselves are excluded from the result.
 */
function isMembersOnlyVisibility(visibility) {
  if (visibility == null) return false;
  return String(visibility).trim().toLowerCase() === 'members only';
}

async function getConnectionsForUser(userId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeEmail(userId);
  if (!uid) return {};

  // 1) Groups the user actively belongs to (member / blind member / admin)
  const { data: userMemberRows, error: e1 } = await supabase
    .from('group_members')
    .select('group_name')
    .ilike('member', uid)
    .in('status', MEMBER_STATUSES);
  if (e1) throw e1;

  const userGroupNames = [...new Set((userMemberRows || []).map(r => r.group_name))];

  // 2) Groups the user owns (always relevant, even if group row was missing from step 3 before)
  const { data: ownedRows, error: eOwned } = await supabase
    .from('groups')
    .select('group_name')
    .ilike('owner', uid);
  if (eOwned) throw eOwned;
  const ownedGroupNames = [...new Set((ownedRows || []).map(r => r.group_name))];

  // 3) Visibility for groups the user is a member of — pick "Members only"
  let memberOnlyGroupNames = [];
  if (userGroupNames.length) {
    const { data: groupRows, error: e2 } = await supabase
      .from('groups')
      .select('group_name, visibility')
      .in('group_name', userGroupNames);
    if (e2) throw e2;
    memberOnlyGroupNames = (groupRows || [])
      .filter(g => isMembersOnlyVisibility(g.visibility))
      .map(g => g.group_name);
  }

  // Union: owned groups + members-only groups user belongs to
  const relevantGroupNames = [...new Set([...ownedGroupNames, ...memberOnlyGroupNames])];
  if (!relevantGroupNames.length) return {};

  // 4) All active members of those groups
  const { data: allMemberRows, error: e3 } = await supabase
    .from('group_members')
    .select('group_name, member')
    .in('group_name', relevantGroupNames)
    .in('status', MEMBER_STATUSES);
  if (e3) throw e3;

  // Canonical group rows — only use real `groups.group_name` values (never owner email as a "group" tag)
  const { data: groupMetaRows, error: eMeta } = await supabase
    .from('groups')
    .select('group_name, owner')
    .in('group_name', relevantGroupNames);
  if (eMeta) throw eMeta;
  const groupMetaByNorm = new Map();
  for (const g of groupMetaRows || []) {
    const key = normalizeEmail(g.group_name);
    if (!key) continue;
    groupMetaByNorm.set(key, g);
  }

  // Build map: normalised member email → [group names from `groups` table]
  const connectionsMap = {};
  for (const row of (allMemberRows || [])) {
    const memberEmail = normalizeEmail(row.member);
    if (memberEmail === uid) continue; // exclude self

    const gnRaw = row.group_name != null ? String(row.group_name).trim() : '';
    const gnNorm = normalizeEmail(gnRaw);
    if (!gnNorm) continue;

    const meta = groupMetaByNorm.get(gnNorm);
    if (!meta) continue; // orphan group_members row with no matching groups row

    // Skip misconfigured rows where group_name equals owner (shows email as a fake "group")
    if (normalizeEmail(meta.owner) === gnNorm) continue;

    const displayName = meta.group_name != null ? String(meta.group_name).trim() : gnRaw;
    if (!displayName) continue;

    if (!connectionsMap[memberEmail]) connectionsMap[memberEmail] = [];
    if (!connectionsMap[memberEmail].includes(displayName)) {
      connectionsMap[memberEmail].push(displayName);
    }
  }
  return connectionsMap;
}

/**
 * All rows from `groups` where owner matches userId (case-insensitive), ordered by group_name.
 */
async function listGroupsOwnedByUser(userId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeEmail(userId);
  if (!uid) return [];

  const { data, error } = await supabase
    .from('groups')
    .select('group_name, visibility')
    .ilike('owner', uid)
    .order('group_name', { ascending: true });
  if (error) throw error;
  return data || [];
}

/**
 * Owner invites a member to their group (inserts group_members with status invited).
 * Verifies userId is the group owner.
 */
async function inviteMemberAsOwner({ group_name, member, ownerUserId }) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeEmail(ownerUserId);
  const gn = (group_name || '').trim();
  const mem = normalizeEmail(member);
  if (!gn || !mem) throw new Error('group_name and member are required');

  const { data: g, error: gErr } = await supabase
    .from('groups')
    .select('owner')
    .eq('group_name', gn)
    .maybeSingle();
  if (gErr) throw gErr;
  if (!g) throw Object.assign(new Error('Group not found'), { status: 404 });
  if (normalizeEmail(g.owner) !== uid) {
    throw Object.assign(new Error('Only the group owner can invite from here'), { status: 403 });
  }

  const { error: insErr } = await supabase
    .from('group_members')
    .insert({ group_name: gn, member: mem, status: 'invited' });
  if (insErr) {
    if (insErr.code === '23505') {
      throw Object.assign(new Error('That person is already in this group or has a pending invite'), { status: 409 });
    }
    throw insErr;
  }
  return { ok: true };
}

/**
 * Returns the email addresses of all 'member' and 'blind member' rows for a group.
 */
async function getGroupMembers(groupName) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const { data, error } = await supabase
    .from('group_members')
    .select('member')
    .eq('group_name', groupName)
    .in('status', ['member', 'blind member']);
  if (error) throw error;
  return (data || []).map(r => r.member);
}

/**
 * Throws if userId is not the group owner or an admin in group_members.
 */
async function assertUserCanManageGroup(groupName, userId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeEmail(userId);
  const gn = (groupName || '').trim();
  if (!gn || !uid) {
    throw Object.assign(new Error('group_name and user are required'), { status: 400 });
  }

  const { data: g, error: gErr } = await supabase
    .from('groups')
    .select('owner')
    .eq('group_name', gn)
    .maybeSingle();
  if (gErr) throw gErr;
  if (!g) throw Object.assign(new Error('Group not found'), { status: 404 });
  if (normalizeEmail(g.owner) === uid) return;

  const { data: adm, error: aErr } = await supabase
    .from('group_members')
    .select('id')
    .eq('group_name', gn)
    .ilike('member', uid)
    .eq('status', 'admin')
    .maybeSingle();
  if (aErr) throw aErr;
  if (!adm) {
    throw Object.assign(new Error('Only group owners and admins can do this'), { status: 403 });
  }
}

/**
 * Groups where the user is the owner (groups.owner) or has status admin in group_members.
 */
async function listGroupsWhereUserCanManageMembers(userId) {
  const uid = normalizeEmail(userId);
  if (!uid) return [];

  const owned = await listGroupsOwnedByUser(userId);
  const names = new Set((owned || []).map(g => g.group_name));

  const userGroups = await listGroupsForUser(userId);
  for (const row of userGroups || []) {
    if (row.is_admin) names.add(row.group_name);
  }

  return [...names]
    .sort((a, b) => a.localeCompare(b, undefined, { sensitivity: 'base' }))
    .map(group_name => ({ group_name }));
}

const MEMBERSHIP_LIST_STATUSES = [...MEMBER_STATUSES, 'invited'];

/**
 * All group_members rows whose person_handle matches (for contact public handle).
 * Each row includes can_remove if viewerUserId may manage that group.
 */
async function getMembershipsByPersonHandleForViewer(person_handle, viewerUserId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const ph = normalizePersonHandle(person_handle);
  if (!ph) return [];

  const { data: rows, error } = await supabase
    .from('group_members')
    .select('id, group_name, status, member, person_handle')
    .ilike('person_handle', ph)
    .in('status', MEMBERSHIP_LIST_STATUSES)
    .order('group_name', { ascending: true });
  if (error) throw error;

  const out = [];
  for (const r of rows || []) {
    let can_remove = false;
    try {
      await assertUserCanManageGroup(r.group_name, viewerUserId);
      can_remove = true;
    } catch (e) {
      can_remove = false;
    }
    out.push({
      id: r.id,
      group_name: r.group_name,
      status: r.status,
      can_remove
    });
  }
  return out;
}

async function removeMembershipByPersonHandle({ group_name, person_handle, actorUserId }) {
  await assertUserCanManageGroup(group_name, actorUserId);
  const supabase = getClient();
  const ph = normalizePersonHandle(person_handle);
  if (!ph) throw new Error('person_handle is required');
  const { error } = await supabase
    .from('group_members')
    .delete()
    .eq('group_name', (group_name || '').trim())
    .ilike('person_handle', ph);
  if (error) throw error;
  return { ok: true };
}

/**
 * Invite a member by email and store person_handle on the row (owner or admin may invite).
 */
async function inviteMemberWithPersonHandle({
  group_name,
  memberEmail,
  person_handle,
  actorUserId
}) {
  await assertUserCanManageGroup(group_name, actorUserId);
  const supabase = getClient();
  const gn = (group_name || '').trim();
  const mem = normalizeEmail(memberEmail);
  const ph = normalizePersonHandle(person_handle);
  if (!gn || !mem) throw new Error('group_name and member email are required');

  const insertPayload = {
    group_name: gn,
    member: mem,
    status: 'invited',
    person_handle: ph || null
  };

  const { error: insErr } = await supabase.from('group_members').insert(insertPayload);
  if (insErr) {
    if (insErr.code === '23505') {
      throw Object.assign(
        new Error('That person is already in this group or has a pending invite'),
        { status: 409 }
      );
    }
    throw insErr;
  }
  return { ok: true };
}

module.exports = {
  isConfigured,
  listGroupsForUser,
  listInvitesForUser,
  respondToGroupInvite,
  createGroup,
  getGroupDetails,
  updateGroup,
  deleteGroup,
  leaveGroup,
  getGroupMembers,
  getConnectionsForUser,
  listGroupsOwnedByUser,
  inviteMemberAsOwner,
  normalizePersonHandle,
  listGroupsWhereUserCanManageMembers,
  getMembershipsByPersonHandleForViewer,
  removeMembershipByPersonHandle,
  inviteMemberWithPersonHandle
};
