/**
 * Friends edges in Supabase (`friends`): each row links user1 and user2.
 * List for a user U: rows where (user1 = U OR user2 = U) and status = 'connected' only.
 *
 * Optional: private_notes text (only visible to the row owner in app UI)
 *
 *   create table if not exists public.friends (
 *     id bigint generated by default as identity primary key,
 *     user1 text not null,
 *     user2 text not null,
 *     status text not null default 'invited',
 *     private_notes text,
 *     created_at timestamptz default now(),
 *     check (user1 <> user2)
 *   );
 *   -- alter table public.friends add column if not exists status text not null default 'invited';
 *   -- alter table public.friends add column if not exists created_at timestamptz default now();
 *   create unique index if not exists friends_pair_unique on public.friends (
 *     least(user1, user2), greatest(user1, user2)
 *   );
 */

let client = null;

function isConfigured() {
  return !!(process.env.SUPABASE_URL && process.env.SUPABASE_SERVICE_ROLE_KEY);
}

function getClient() {
  if (client) return client;
  if (!isConfigured()) return null;
  const { createClient } = require('@supabase/supabase-js');
  client = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
  return client;
}

function normalizeId(s) {
  return s != null ? String(s).trim() : '';
}

function normalizeEmail(s) {
  return s != null ? String(s).trim().toLowerCase() : '';
}

/**
 * True if a friends row exists linking the two users with status connected or invited.
 */
async function hasAnyFriendshipWith(userId, otherEmail) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const u = normalizeEmail(userId);
  const o = normalizeEmail(otherEmail);
  if (!u || !o) return false;

  const { data: r1, error: e1 } = await supabase
    .from('friends')
    .select('id')
    .in('status', ['connected', 'invited'])
    .ilike('user1', u)
    .ilike('user2', o)
    .maybeSingle();
  if (e1) throw e1;
  if (r1) return true;

  const { data: r2, error: e2 } = await supabase
    .from('friends')
    .select('id')
    .in('status', ['connected', 'invited'])
    .ilike('user1', o)
    .ilike('user2', u)
    .maybeSingle();
  if (e2) throw e2;
  return !!r2;
}

/** Other party in the row when viewer is one of user1 / user2. */
function otherUser(row, viewerId) {
  const v = normalizeId(viewerId);
  const u1 = normalizeId(row.user1);
  const u2 = normalizeId(row.user2);
  if (u1 === v) return u2;
  if (u2 === v) return u1;
  return '';
}

/**
 * Connected friendship rows for this user (`status` = 'connected' only), plus `other_user`.
 */
async function listFriendsForUser(userId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeId(userId);
  if (!uid) return [];

  const { data: as1, error: e1 } = await supabase
    .from('friends')
    .select('*')
    .eq('user1', uid)
    .eq('status', 'connected');
  if (e1) throw e1;
  const { data: as2, error: e2 } = await supabase
    .from('friends')
    .select('*')
    .eq('user2', uid)
    .eq('status', 'connected');
  if (e2) throw e2;

  const byId = new Map();
  for (const row of [...(as1 || []), ...(as2 || [])]) {
    byId.set(row.id, row);
  }
  const rows = Array.from(byId.values());
  rows.sort((a, b) => {
    const oa = otherUser(a, uid);
    const ob = otherUser(b, uid);
    return oa.localeCompare(ob, undefined, { sensitivity: 'base' });
  });

  return rows.map((row) => ({
    id: row.id,
    user1: row.user1,
    user2: row.user2,
    status: row.status,
    created_at: row.created_at,
    other_user: otherUser(row, uid),
    private_notes: row.private_notes != null ? row.private_notes : null
  }));
}

/**
 * Updates private_notes on a friends row. Caller must be user1 or user2.
 */
async function updateFriendPrivateNotes(id, userId, privateNotes) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeId(userId);
  const { data: row, error: selErr } = await supabase
    .from('friends')
    .select('id, user1, user2')
    .eq('id', id)
    .maybeSingle();
  if (selErr) throw selErr;
  if (!row) return false;
  const u1 = normalizeId(row.user1);
  const u2 = normalizeId(row.user2);
  if (u1 !== uid && u2 !== uid) return false;
  const val =
    privateNotes == null || String(privateNotes).trim() === ''
      ? null
      : String(privateNotes).trim();
  const { error } = await supabase.from('friends').update({ private_notes: val }).eq('id', id);
  if (error) throw error;
  return true;
}

async function insertFriend({ user_id, friend_id, private_notes }) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const a = normalizeId(user_id);
  const b = normalizeId(friend_id);
  if (!a || !b) throw new Error('user_id and friend_id are required');
  if (a.toLowerCase() === b.toLowerCase()) throw new Error('Cannot add yourself as a friend');

  const row = { user1: a, user2: b, status: 'invited' };
  if (private_notes !== undefined && private_notes != null && String(private_notes).trim() !== '') {
    row.private_notes = String(private_notes).trim();
  }
  const { data, error } = await supabase.from('friends').insert(row).select('*').single();
  if (error) throw error;
  return data;
}

async function deleteFriendForUser(id, userId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeId(userId);
  const { data: row, error: selErr } = await supabase
    .from('friends')
    .select('id, user1, user2')
    .eq('id', id)
    .maybeSingle();
  if (selErr) throw selErr;
  if (!row) return false;
  const u1 = normalizeId(row.user1);
  const u2 = normalizeId(row.user2);
  if (u1 !== uid && u2 !== uid) return false;
  const { error } = await supabase.from('friends').delete().eq('id', id);
  if (error) throw error;
  return true;
}

/**
 * Invites where this user is user2 (invitee) and status is invited.
 */
async function listIncomingInvites(userId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeId(userId);
  if (!uid) return [];
  const { data, error } = await supabase
    .from('friends')
    .select('*')
    .eq('user2', uid)
    .eq('status', 'invited')
    .order('id', { ascending: true });
  if (error) throw error;
  return data || [];
}

/**
 * Invitee (user2) accepts or rejects. Accept → connected; reject → rejected.
 */
async function respondToInvite(id, inviteeUserId, action) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeId(inviteeUserId);
  const newStatus = action === 'accept' ? 'connected' : 'rejected';
  if (action !== 'accept' && action !== 'reject') {
    throw new Error('action must be accept or reject');
  }

  const { data: row, error: selErr } = await supabase
    .from('friends')
    .select('id, user1, user2, status')
    .eq('id', id)
    .maybeSingle();
  if (selErr) throw selErr;
  if (!row) return false;
  if (normalizeId(row.user2) !== uid) return false;
  if (normalizeId(row.status) !== 'invited') return false;

  const { error } = await supabase.from('friends').update({ status: newStatus }).eq('id', id);
  if (error) throw error;
  return true;
}

module.exports = {
  isConfigured,
  listFriendsForUser,
  listIncomingInvites,
  insertFriend,
  deleteFriendForUser,
  respondToInvite,
  updateFriendPrivateNotes,
  hasAnyFriendshipWith
};
