/**
 * Friends edges in Supabase (`friends`): each row links user1 and user2 by **public profile handle**
 * (normalized, no `@`). List for a user U: rows where (user1 = U OR user2 = U) and status = 'connected'.
 *
 *   create table if not exists public.friends (
 *     id bigint generated by default as identity primary key,
 *     user1 text not null,
 *     user2 text not null,
 *     status text not null default 'invited',
 *     created_at timestamptz default now(),
 *     check (user1 <> user2)
 *   );
 *   -- user1 = inviter handle; user2 = invitee handle; status e.g. invited | connected
 *   create unique index if not exists friends_pair_unique on public.friends (
 *     least(user1, user2), greatest(user1, user2)
 *   );
 */

let client = null;

const supabaseGroups = require('./supabase-groups');
const supabaseProfiles = require('./supabase-profiles');

function isConfigured() {
  return !!(process.env.SUPABASE_URL && process.env.SUPABASE_SERVICE_ROLE_KEY);
}

function getClient() {
  if (client) return client;
  if (!isConfigured()) return null;
  const { createClient } = require('@supabase/supabase-js');
  client = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
  return client;
}

function normalizeEmail(s) {
  return s != null ? String(s).trim().toLowerCase() : '';
}

function normalizePersonHandle(s) {
  return s != null ? String(s).trim().replace(/^@+/, '').toLowerCase() : '';
}

/** Email → profile handle, or bare handle / `@handle` string → normalized handle. */
async function resolvePersonHandleToken(token) {
  const raw = (token || '').trim();
  if (!raw) return null;
  const lower = raw.toLowerCase();
  if (lower.includes('@') && !/^@[^@]+$/.test(raw)) {
    return await supabaseGroups.personHandleForUserEmail(lower);
  }
  return normalizePersonHandle(raw.replace(/^@+/, '')) || null;
}

/** True if this row belongs to viewer (by handle, or legacy email stored in user1/user2). */
async function rowInvolvesViewer(row, viewerEmail) {
  const uid = normalizeEmail(viewerEmail);
  if (!uid || !row) return false;
  const vh = await supabaseGroups.personHandleForUserEmail(uid);
  const u1 = normalizePersonHandle(row.user1);
  const u2 = normalizePersonHandle(row.user2);
  if (vh && (u1 === vh || u2 === vh)) return true;
  if (normalizeEmail(row.user1) === uid || normalizeEmail(row.user2) === uid) return true;
  return false;
}

/**
 * True if a friends row exists linking the two users with status connected or invited.
 * Accepts viewer email + other party email or handle string.
 */
async function hasAnyFriendshipWith(userId, otherIdentifier) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const u = normalizeEmail(userId);
  if (!u) return false;
  const uh = await supabaseGroups.personHandleForUserEmail(u);
  const oh = await resolvePersonHandleToken(otherIdentifier);
  if (!uh || !oh) return false;
  if (uh === oh) return false;

  const { data: h1, error: eh1 } = await supabase
    .from('friends')
    .select('id')
    .in('status', ['connected', 'invited'])
    .eq('user1', uh)
    .eq('user2', oh)
    .maybeSingle();
  if (eh1) throw eh1;
  if (h1) return true;

  const { data: h2, error: eh2 } = await supabase
    .from('friends')
    .select('id')
    .in('status', ['connected', 'invited'])
    .eq('user1', oh)
    .eq('user2', uh)
    .maybeSingle();
  if (eh2) throw eh2;
  if (h2) return true;

  const o = normalizeEmail(otherIdentifier);
  if (!o) return false;

  const { data: r1, error: e1 } = await supabase
    .from('friends')
    .select('id')
    .in('status', ['connected', 'invited'])
    .ilike('user1', u)
    .ilike('user2', o)
    .maybeSingle();
  if (e1) throw e1;
  if (r1) return true;

  const { data: r2, error: e2 } = await supabase
    .from('friends')
    .select('id')
    .in('status', ['connected', 'invited'])
    .ilike('user1', o)
    .ilike('user2', u)
    .maybeSingle();
  if (e2) throw e2;
  return !!r2;
}

/**
 * Other party handle when viewer is one of user1 / user2.
 */
function otherUser(row, viewerEmail, viewerHandle) {
  const ve = normalizeEmail(viewerEmail);
  const vh = viewerHandle ? normalizePersonHandle(viewerHandle) : '';
  const u1h = normalizePersonHandle(row.user1);
  const u2h = normalizePersonHandle(row.user2);
  if (vh) {
    if (u1h === vh) return row.user2;
    if (u2h === vh) return row.user1;
  }
  const u1e = normalizeEmail(row.user1);
  const u2e = normalizeEmail(row.user2);
  if (ve && u1e === ve) return row.user2;
  if (ve && u2e === ve) return row.user1;
  return row.user2 || row.user1;
}

/**
 * Connected friendship rows for this user (`status` = 'connected' only), plus `other_user` (handle).
 */
async function listFriendsForUser(userId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uidEmail = normalizeEmail(userId);
  if (!uidEmail) return [];

  const viewerHandle = await supabaseGroups.personHandleForUserEmail(uidEmail);

  const byId = new Map();
  const add = arr => {
    for (const row of arr || []) {
      byId.set(row.id, row);
    }
  };

  if (viewerHandle) {
    const { data, error } = await supabase
      .from('friends')
      .select('*')
      .eq('user1', viewerHandle)
      .eq('status', 'connected');
    if (error) throw error;
    add(data);

    const { data: asUser2, error: e2 } = await supabase
      .from('friends')
      .select('*')
      .eq('user2', viewerHandle)
      .eq('status', 'connected');
    if (e2) throw e2;
    add(asUser2);
  }

  const { data: legacy2, error: le2 } = await supabase
    .from('friends')
    .select('*')
    .ilike('user2', uidEmail)
    .eq('status', 'connected');
  if (le2) throw le2;
  add(legacy2);

  const { data: legacy1, error: le1 } = await supabase
    .from('friends')
    .select('*')
    .ilike('user1', uidEmail)
    .eq('status', 'connected');
  if (le1) throw le1;
  add(legacy1);

  const rows = Array.from(byId.values());
  rows.sort((a, b) => {
    const oa = otherUser(a, uidEmail, viewerHandle);
    const ob = otherUser(b, uidEmail, viewerHandle);
    return oa.localeCompare(ob, undefined, { sensitivity: 'base' });
  });

  const out = [];
  for (const row of rows) {
    const other = otherUser(row, uidEmail, viewerHandle);
    let other_user_email = null;
    let friend_display_name = null;
    const oh = normalizePersonHandle(other);
    if (oh && supabaseProfiles.isConfigured()) {
      try {
        const p = await supabaseProfiles.getProfileByHandle(oh);
        if (p) {
          if (p.email) other_user_email = normalizeEmail(p.email);
          if (p.name != null && String(p.name).trim() !== '') {
            friend_display_name = String(p.name).trim();
          }
        }
      } catch (e) {
        /* ignore */
      }
    }
    out.push({
      id: row.id,
      user1: row.user1,
      user2: row.user2,
      status: row.status,
      created_at: row.created_at,
      other_user: other,
      friend_display_name,
      other_user_email
    });
  }
  return out;
}

async function insertFriend({ user_id, friend_id }) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const inviterEmail = normalizeEmail(user_id);
  if (!inviterEmail) {
    throw new Error('user_id is required');
  }
  const inviteeHandle = await resolvePersonHandleToken(friend_id);
  if (!inviteeHandle) {
    throw new Error('Could not resolve friend to a public handle. Use their email or @handle.');
  }
  const inviteeProfile = await supabaseProfiles.getProfileByHandle(inviteeHandle);
  if (!inviteeProfile || !inviteeProfile.handle) {
    throw new Error('That handle could not be found');
  }

  const inviterHandle = await supabaseGroups.personHandleForUserEmail(inviterEmail);
  if (!inviterHandle) {
    throw new Error('Set a public handle on your profile before inviting friends.');
  }
  if (inviterHandle === inviteeHandle) {
    throw new Error('Cannot add yourself as a friend');
  }

  const row = {
    user1: inviterHandle,
    user2: inviteeHandle,
    status: 'invited'
  };
  const { data, error } = await supabase.from('friends').insert(row).select('*').single();
  if (error) throw error;
  return data;
}

async function deleteFriendForUser(id, userId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uid = normalizeEmail(userId);
  const { data: row, error: selErr } = await supabase
    .from('friends')
    .select('id, user1, user2')
    .eq('id', id)
    .maybeSingle();
  if (selErr) throw selErr;
  if (!row) return false;
  if (!(await rowInvolvesViewer(row, uid))) return false;
  const { error } = await supabase.from('friends').delete().eq('id', id);
  if (error) throw error;
  return true;
}

/**
 * Invites where this user is user2 (invitee) and status is invited.
 */
async function listIncomingInvites(userId) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uidEmail = normalizeEmail(userId);
  if (!uidEmail) return [];

  const inviteeHandle = await supabaseGroups.personHandleForUserEmail(uidEmail);
  const byId = new Map();
  const add = arr => {
    for (const row of arr || []) {
      byId.set(row.id, row);
    }
  };

  if (inviteeHandle) {
    const { data, error } = await supabase
      .from('friends')
      .select('*')
      .eq('user2', inviteeHandle)
      .eq('status', 'invited')
      .order('id', { ascending: true });
    if (error) throw error;
    add(data);
  }

  const { data: legacy, error: legErr } = await supabase
    .from('friends')
    .select('*')
    .ilike('user2', uidEmail)
    .eq('status', 'invited')
    .order('id', { ascending: true });
  if (legErr) throw legErr;
  add(legacy);

  const rows = Array.from(byId.values());
  rows.sort((a, b) => (a.id || 0) - (b.id || 0));
  return rows;
}

/**
 * Invitee (user2) accepts or rejects. Accept → connected; reject → rejected.
 */
async function respondToInvite(id, inviteeUserId, action) {
  const supabase = getClient();
  if (!supabase) throw new Error('Supabase not configured');
  const uidEmail = normalizeEmail(inviteeUserId);
  const inviteeHandle = uidEmail ? await supabaseGroups.personHandleForUserEmail(uidEmail) : null;
  const newStatus = action === 'accept' ? 'connected' : 'rejected';
  if (action !== 'accept' && action !== 'reject') {
    throw new Error('action must be accept or reject');
  }

  const { data: row, error: selErr } = await supabase
    .from('friends')
    .select('id, user1, user2, status')
    .eq('id', id)
    .maybeSingle();
  if (selErr) throw selErr;
  if (!row) return false;

  const rowU2h = normalizePersonHandle(row.user2);
  const isInvitee =
    (inviteeHandle && rowU2h === inviteeHandle) ||
    (uidEmail && normalizeEmail(row.user2) === uidEmail);
  if (!isInvitee) return false;
  if (String(row.status || '').trim().toLowerCase() !== 'invited') return false;

  const { error } = await supabase.from('friends').update({ status: newStatus }).eq('id', id);
  if (error) throw error;
  return true;
}

module.exports = {
  isConfigured,
  listFriendsForUser,
  listIncomingInvites,
  insertFriend,
  deleteFriendForUser,
  respondToInvite,
  hasAnyFriendshipWith
};
